# -*- coding: utf-8 -*-
"""p1hw1_WheatleDale.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kdAvTpvUqYkam7bYFJMTsHVZpG2J7X8t
"""

#Dale Wheatle
#02/10/2025
#p1hw1
#calculating exponenets
#THIS IS MY UPDATED CODE!! my first submission involed me hard codding the integers, sorry 🤞


base_value=int(input("your base value:"))
exponent=int(input("your exponent"))
result=base_value**exponent
print("enter an integer as the base value:",base_value)
print("enter an integer as the exponent:",exponent)
print(base_value,"raised to the power of",exponent,"is",result)
print()
print()

print("------Addition and Subtraction------")
print()
starting_integer=int(input("starting integer:"))
add_integer=int(input("integer to add:"))
sub_integer=int(input("integer to subtract:"))
result=starting_integer+add_integer-sub_integer
print()
print("enter a starting integer:",starting_integer)
print("enter an integer to add:",add_integer)
print("enter an integer to subtract:",sub_integer)
print()
print(starting_integer,"+",add_integer,"-",sub_integer,"is equal to",result)

