# -*- coding: utf-8 -*-
"""P1HW2_WheatleDale.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pwb9hnmvYL3oKp-vQcuXYl-AyIV4HQqY
"""

#Dale Wheatle
#2/10/2025
#P1HW2
#creating a program that allows the user to caculate thier budget.


budget=float(input("Enter Budget:"))
Travel_destination=input("enter your travel destination:")
gas=float(input("how much do you think you will spend on gas?:"))
hotel=float(input("how much do you need for lodging?:"))
food=float(input("how do you need for food?:"))
remaining_balance=budget-(gas+hotel+food)
print()
print("--------Travel exspenses-------")

print("Location:",Travel_destination)
print("inital Budget:",budget)
print("gas:",gas)
print("lodging:",hotel)
print("Food:",food)
print("Remaining Balance:",remaining_balance)